[package]
name = "my-near-cli-dialoguer-strum-2"
version = "0.1.0"
authors = ["FroVolod <frol_off@meta.ua>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
dialoguer = "0.7"
strum = "0.20"
strum_macros = "0.20"
smart-default = "0.6.0"
derive_more = "0.99.9"

async-recursion = "0.3.2"

actix = "0.9"
actix-web = { version = "2", features = [ "openssl" ] }
openssl-probe = { version = "0.1.2" }



# near-crypto = { git = "https://github.com/nearprotocol/nearcore", rev="1cb93029cb41d224b1a6c77caf90414ff64e3d47" }
# near-primitives = { git = "https://github.com/nearprotocol/nearcore", rev="1cb93029cb41d224b1a6c77caf90414ff64e3d47" }
# near-jsonrpc-client = { git = "https://github.com/nearprotocol/nearcore", rev="1cb93029cb41d224b1a6c77caf90414ff64e3d47" }


near-crypto = { git = "https://github.com/nearprotocol/nearcore", rev="29fcaf3b8c81a4c0371d105054ce251355382a77" }
near-primitives = { git = "https://github.com/nearprotocol/nearcore", rev="29fcaf3b8c81a4c0371d105054ce251355382a77" }
near-jsonrpc-client = { git = "https://github.com/nearprotocol/nearcore", rev="29fcaf3b8c81a4c0371d105054ce251355382a77" }
